# Generated by Django 5.1.2 on 2024-11-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userproduct',
            name='stack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, editable=False, max_digits=10),
        ),
    ]
