# Generated by Django 5.1.2 on 2024-11-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_design', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userproduct',
            old_name='available_sizes',
            new_name='size',
        ),
    ]
