# Generated by Django 5.1.2 on 2024-11-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shope', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_colors',
        ),
        migrations.RemoveField(
            model_name='userdesign',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='userdesign',
            name='Size',
        ),
        migrations.RemoveField(
            model_name='userdesign',
            name='user',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.DeleteModel(
            name='UserDesign',
        ),
    ]
